packages: []
overrides:
  is-core-module: npm:@no-shims/is-core-module

catalog:
  '@eslint/js': ^9.29.0
  eslint: ^9.29.0
  eslint-flat-config-utils: ^2.1.0
  globals: ^16.2.0
  local-pkg: ^1.1.1

catalogs:
  dev:
    '@eslint/config-inspector': ^1.1.0
    '@sxzz/prettier-config': ^2.2.1
    '@types/node': ^24.0.3
    ansis: ^4.1.0
    bumpp: ^10.2.0
    eslint-typegen: ^2.2.0
    prettier: ^3.5.3
    tsdown: ^0.12.8
    tsx: ^4.20.3
    typescript: ^5.8.3

  parsers:
    jsonc-eslint-parser: ^2.4.0
    vue-eslint-parser: ^10.1.3
    yaml-eslint-parser: ^1.3.0

  plugins:
    '@eslint-community/eslint-plugin-eslint-comments': ^4.5.0
    '@eslint/markdown': ^6.6.0
    '@unocss/eslint-plugin': ^66.2.3
    eslint-config-flat-gitignore: ^2.1.0
    eslint-config-prettier: ^10.1.5
    eslint-plugin-antfu: ^3.1.1
    eslint-plugin-command: ^3.3.0
    eslint-plugin-de-morgan: ^1.3.0
    eslint-plugin-import-x: ^4.15.2
    eslint-plugin-jsdoc: ^51.1.1
    eslint-plugin-jsonc: ^2.20.1
    eslint-plugin-n: ^17.20.0
    eslint-plugin-perfectionist: ^4.15.0
    eslint-plugin-pnpm: ^1.0.0
    eslint-plugin-prettier: ^5.5.0
    eslint-plugin-regexp: ^2.9.0
    eslint-plugin-sxzz: ^0.3.0
    eslint-plugin-unicorn: ^59.0.1
    eslint-plugin-unused-imports: ^4.1.4
    eslint-plugin-vue: ^10.2.0
    eslint-plugin-yml: ^1.18.0
    typescript-eslint: ^8.34.1
